spring.application.name=moodnest

# Conexión a MongoDB 
spring.data.mongodb.uri=mongodb://mongo-server:27017/moodnest_db

# (Opcional) Para ver las consultas exactas en la consola durante el desarrollo
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Configuración JWT
jwt.secret=MoodNestTFG2026ClaveSecretaSuperSeguraParaFirmarTokens123456789
jwt.expiration=86400000