spring.application.name=moodnest

# Conexión a MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/moodnest_db

# (Opcional) Para ver las consultas exactas en la consola durante el desarrollo
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Configuración JWT (Clave secreta de 256 bits y expiración en milisegundos - 24h)
jwt.secret=MoodNestTFG2026ClaveSecretaSuperSeguraParaFirmarTokens123456789
jwt.expiration=86400000